# -*- coding: utf-8 -*-
"""assn9_dumb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkhhI_oRWPxyqfzZQwlbE6KEYxw8Y6Vt
"""

from guidance import models, gen, select

falcon = models.Transformers("tiiuae/falcon-rw-1b")

lm = falcon + "Once upon a time, " + gen(max_tokens=10)
print(lm)  # Once upon a time, there was a little girl who was very shy.

lm = falcon + "Write a sentence about the printing press. " + gen(stop=["\n", ".", "!"])
print(lm)
# The printing press was invented by Johannes Gutenberg in 1450

lm = falcon + "1, 2, 3," + gen(max_tokens=50, stop="11")
print(lm)
# 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

lm = falcon + "I like the color " + select(["cyan", "grey", "purple"])
print(lm)  # I like the color purple

# lm = falcon + "Generate an email: " + gen(regex="\w+@\w+.com")
# print(lm)  # Generate an email: theoreticaly@gmail.com

user_input = "Tell me about black holes."

prompt = f"""
Format the following conversation in HTML with clearly marked user and assistant messages:

User: {user_input}
Assistant:
<div class="exchange">
  <div class="user"><strong>User:</strong> {user_input}</div>
  <div class="assistant"><strong>Assistant:</strong> <p>"""  # stop at </p> to keep HTML valid

lm = falcon + prompt + gen(stop="</p>")
html_response = str(lm) + "</p></div></div>"  # manually close the tags

print(html_response)


# Function to get structured HTML output
def chat_html_response(user_message):
    prompt = f"""
Format the following as HTML with user and assistant messages.
Wrap user in <div class="user"> and assistant response in <div class="assistant">.
Use a <p> tag for the assistant's response.

User: {user_message}
Assistant:
<div class="exchange">
  <div class="user"><strong>User:</strong> {user_message}</div>
  <div class="assistant"><strong>Assistant:</strong> <p>"""

    # Stop generation at end of paragraph
    response = falcon + prompt + gen(stop="</p>")

    return str(response) + "</p></div></div>"


# Test it
user_input = "Who am I?"
html_output = chat_html_response(user_input)

print(html_output)
