# -*- coding: utf-8 -*-
"""Assn8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxCV0JdE-1YEcwKDT_U-U5fXRPi3e4hQ
"""

from huggingface_hub import login
login()

# Commented out IPython magic to ensure Python compatibility.
#  %%capture
!pip install "vllm>=0.3.1"

from google.colab import drive
drive.mount('/content/drive')

ls "/content/drive/MyDrive/Misc College/LLMs/assn5_lora"

!python3 -m vllm.entrypoints.openai.api_server \
  --model meta-llama/meta-Llama-3.1-8B-Instruct \
  --enable-lora \
  --lora-modules assn5="/content/drive/MyDrive/Misc College/LLMs/assn5_lora" \
  --device cuda\
  --max-lora-rank 16\
  --gpu-memory-utilization 0.6

!ps aux | grep vllm

import requests

url = "http://127.0.0.1:8000/v1/chat/completions"

data = {
    "model": "assn5",  # This is your LoRA adapter name
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is the capital of France?"}
    ],
    "max_tokens": 100,
    "temperature": 0.7
}

response = requests.post(url, json=data)
print(response.json())