# -*- coding: utf-8 -*-
"""Assn10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DW0WjKCDoQTOIVCBxfJ7aSI7VcfvCa_
"""

# Install DSPy and any required extras
!pip install dspy

import dspy

dspy.settings.configure(
    lm=dspy.LM(
        model="huggingface/tiiuae/Falcon-7B-Instruct",
        api_key = ""
    )
)

class JeopardyReverser(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate_question = dspy.Predict("answer -> question")

    def forward(self, answer):
        return self.generate_question(answer=answer)

prompt = "In this city, lies the  Eiffel Tower"

# Run it!
reverser = JeopardyReverser()
result = reverser(prompt)

print("🔎 Given the answer:", "Prompt")
print("❓ Generated question:", result.question)

import dspy

# Set your Hugging Face API key + Falcon model
dspy.settings.configure(
    lm=dspy.LM(
        # model="huggingface/tiiuae/Falcon-7B-Instruct",
        model ="meta-llama/Llama-3.1-8B-Instruct",
        api_key=""
    )
)

# Define your base module
predictor = dspy.ChainOfThought("clue -> reasoning, question")

# Add example Q&A pairs for bootstrapping
fewshot_examples = [
    {
        "clue": "In this city lies the Eiffel Tower",
        "reasoning": "The Eiffel Tower is a famous monument located in a major European capital, Paris.",
        "question": "Where is Paris?"
    },
  {
        "clue": "The 1984 movie character introduced in 1984 with only 21 lines and 133 words",
        "reasoning": "The 1984 movie character who only speaks 21 lines and 133 words is a well-known cyborg from a James Cameron film.",
        "question": "Who is the terminator"
    },
    {
        "clue": "In Free Willy, Willy is this type of creature.",
        "reasoning": "In Free Willy, the animal saved by the boy is a large marine mammal often confused with an orca.",
        "question": "What type of animal is Willy in the film Free Willy?"
    },
    {
        "clue": "The tallest mountain in the world located Nepal ",
        "reasoning": "This is the tallest mountain on Earth and a popular destination for climbers seeking extreme heights.",
        "question": "What is Mountain Everest?"
    }
]

# Use BootstrapFewShot to compile a working model
compiler = dspy.BootstrapFewShot(metric=None)
compiled_program = compiler.compile(predictor, trainset=fewshot_examples)

# Correct few-shot examples (wrapped with dspy.Example)
fewshot_examples = [
    dspy.Example(
        clue="In this city lies the Eiffel Tower",
        reasoning="The Eiffel Tower is a famous monument located in a major European capital.",
        question="Where is Paris?"
    ).with_inputs("clue"),

    dspy.Example(
        clue="The 1984 movie character introduced in 1984 with only 21 lines and 133 words",
        reasoning="This 1984 cyborg had very little dialogue and is iconic in sci-fi film.",
        question="Who is the Terminator?"
    ).with_inputs("clue"),

    dspy.Example(
        clue="In Free Willy, Willy is this type of creature.",
        reasoning="Willy is an orca, or killer whale, featured in the film Free Willy.",
        question="What is a killer whale?"
    ).with_inputs("clue"),

    dspy.Example(
        clue="The tallest mountain in the world located in Nepal",
        reasoning="Mount Everest is the tallest mountain on Earth and is in Nepal.",
        question="What is Mount Everest?"
    ).with_inputs("clue")
]



# Use BootstrapFewShot to compile a working model
compiler = dspy.BootstrapFewShot(metric=None)
compiled_program = compiler.compile(predictor, trainset=fewshot_examples)

# Now run with your prompt
prompt = "This city is biggest city in the United States."
result = compiled_program(clue=prompt)

print(" Given the answer:", prompt)
print("Reasoning:", result.reasoning)
print("Generated question:", result.question)