# -*- coding: utf-8 -*-
"""Assn10_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TnnvfJ5m5zVdLw-ATkp3Icvk0_N7Tva
"""

# Install DSPy and any required extras
!pip install transformers accelerate dspy

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Load the model locally
model_id = "tiiuae/falcon-rw-1b"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)

#  Create a text generation pipeline
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Define few-shot examples for manual prompting
fewshot_examples = [
    ("In this city lies the Eiffel Tower", "Where is Paris?"),
    ("The 1984 movie character introduced in 1984 with only 21 lines and 133 words", "Who is the Terminator?"),
    ("In Free Willy, Willy is this type of creature.", "What is a killer whale?"),
    ("The tallest mountain in the world located in Nepal", "What is Mount Everest?")
]

# Function to build few-shot prompt
def build_prompt(clue):
    prompt = "Generate a trivia-style question from a clue.\n\n"
    for ex_clue, ex_question in fewshot_examples:
        prompt += f"Clue: {ex_clue}\nQuestion: {ex_question}\n\n"
    prompt += f"Clue: {clue}\nQuestion:"
    return prompt

# Your input clue
clue = "This mountain is the tallest mountain on Earth."
final_prompt = build_prompt(clue)

# Generate the output
output = generator(final_prompt, max_new_tokens=50, do_sample=True, temperature=0.7)[0]["generated_text"]

# Extract the generated question
generated_question = output.split("Question:")[-1].strip().split("\n")[0]

# Print results
print("Given clue:", clue)
print("Generated question:", generated_question)