from unsloth import FastLanguageModel, PatchFastRL
from vllm import SamplingParams

# import unsloth
from unsloth import is_bfloat16_supported
from trl import GRPOConfig, GRPOTrainer
from datasets import load_dataset
from datasets import concatenate_datasets


# -*- coding: utf-8 -*-
"""RileyAssn6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141ifcCY-kvtGcbxRAvG4xvvj4pto61N7

### Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Skip restarting message in Colab
# import sys; modules = list(sys.modules.keys())
# for x in modules: sys.modules.pop(x) if "PIL" in x or "google" in x else None
#
# !pip install unsloth vllm
# !pip install --upgrade pillow
# # If you are running this notebook on local, you need to install `diffusers` too
# # !pip install diffusers
# # Temporarily install a specific TRL nightly version
# !pip install git+https://github.com/huggingface/trl.git@e95f9fb74a3c3647b86f251b7e230ec51c64b72b

"""### Unsloth

Use `PatchFastRL` before all functions to patch GRPO and other RL algorithms!
"""


# import torch
PatchFastRL("GRPO", FastLanguageModel)

"""Load up `Llama 3.1 8B Instruct`, and set parameters"""


# print(torch.__version__,unsloth.__version__)
max_seq_length = 512  # Can increase for longer reasoning traces
lora_rank = 16  # Larger rank = smarter, but slower

### using ghe model 3.2-1B

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="meta-llama/Llama-3.2-1B-Instruct",
    max_seq_length=max_seq_length,
    load_in_4bit=True,  # False for LoRA 16bit
    fast_inference=True,  # Enable vLLM fast inference
    max_lora_rank=lora_rank,
    gpu_memory_utilization=0.6,  # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,  # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],  # Remove QKVO if out of memory
    lora_alpha=lora_rank,
    use_gradient_checkpointing="unsloth",  # Enable long context finetuning
    random_state=3407,
)

"""### Data Prep
<a name="Data"></a>

Using the wikipedia dataset
"""

# import re
# from datasets import load_dataset, Dataset


# Load Wikipedia English dataset
wikipedia_dataset = load_dataset("wikipedia", "20220301.simple")

# def preprocess_wiki(example):
#     tokenized = tokenizer(
#         example["text"],
#         truncation=True,
#         padding="max_length",
#         max_length=512
#     )
#     return {
#         "prompt": example["text"],  # Treat the article as a "prompt"
#         "input_ids": tokenized["input_ids"],
#         "attention_mask": tokenized["attention_mask"],
#     }

# # Apply the fix to the dataset
# tokenized_wiki = wikipedia_dataset.map(
#     preprocess_wiki,
#     batched=True,
#     remove_columns=["text"],
#     num_proc=2
# )


# Format into prompts
def format_wiki_as_prompt(example):
    example["prompt"] = f"Tell me about this topic:\n\n{example['text']}"
    return example


formatted_wiki = wikipedia_dataset.map(format_wiki_as_prompt, remove_columns=["text"])


def tokenize_function(examples):
    tokenized_batch = tokenizer(
        examples["prompt"],
        padding="max_length",
        truncation=True,
        max_length=512,
    )

    # Ensure correct processing for batched input
    truncated_prompts = [
        tokenizer.decode(input_ids[:512], skip_special_tokens=True)
        for input_ids in tokenized_batch["input_ids"]
    ]

    return {
        "prompt": truncated_prompts,  # Store trimmed prompts
        "input_ids": [
            ids[:512] for ids in tokenized_batch["input_ids"]
        ],  # Trim input_ids
        "attention_mask": [
            mask[:512] for mask in tokenized_batch["attention_mask"]
        ],  # Trim attention mask
    }


# Apply tokenization with batch processing
tokenized_wiki = formatted_wiki.map(tokenize_function, batched=True)

"""Jeopardy data"""

jeopardy_dataset = load_dataset("csv", data_files="/content/JEOPARDY_CSV.csv")


def preprocess_jeopardy(batch):
    """Processes Jeopardy data into structured Q&A format WITHOUT category."""
    questions = batch[" Question"]  # Extract list of questions
    answers = batch[" Answer"]  # Extract list of answers

    formatted_prompts = [f"Question: {q}" for q in questions]  # Format all prompts

    tokenized = tokenizer(
        formatted_prompts, truncation=True, padding="max_length", max_length=512
    )

    return {
        "prompt": formatted_prompts,  # Store human-readable text (as a list!)
        "answer": answers,  # List of answers
        "input_ids": tokenized["input_ids"],  # List of tokenized input IDs
        "attention_mask": tokenized["attention_mask"],  # List of attention masks
    }


# Apply preprocessing
jeopardy_processed = jeopardy_dataset.map(preprocess_jeopardy, batched=True)

"""riddles"""

riddle_dataset = load_dataset("csv", data_files="/content/Riddles.csv")

{
    "prompt": "Riddle: I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
    "answer": "An echo",
    "input_ids": [...],  # Tokenized prompt
    "attention_mask": [...],
}


def preprocess_riddles(batch):
    """Processes riddle data into structured Q&A format WITHOUT hint."""
    riddles = batch["Riddle"]  # Extract list of riddles
    answers = batch["Answer"]  # Extract list of answers

    formatted_prompts = [
        f"Riddle: {r}" for r in riddles
    ]  # Format prompts without the hint

    tokenized = tokenizer(
        formatted_prompts, truncation=True, padding="max_length", max_length=512
    )

    return {
        "prompt": formatted_prompts,  # List of prompts
        "answer": answers,  # List of answers
        "input_ids": tokenized["input_ids"],  # List of tokenized input IDs
        "attention_mask": tokenized["attention_mask"],  # List of attention masks
    }


# Apply preprocessing
riddle_processed = riddle_dataset.map(preprocess_riddles, batched=True)

"""join data"""

# print(riddle_processed['train'])
# print(jeopardy_processed['train'])
# print(tokenized_wiki['train'])

"""Merging the datasets"""

# Keep only the necessary columns (no need to add "answer" to Wikipedia)
wikipedia_processed = tokenized_wiki.select_columns(
    ["prompt", "input_ids", "attention_mask"]
)
jeopardy_processed = jeopardy_processed.select_columns(
    ["prompt", "answer", "input_ids", "attention_mask"]
)
riddle_processed = riddle_processed.select_columns(
    ["prompt", "answer", "input_ids", "attention_mask"]
)


final_dataset = concatenate_datasets(
    [
        wikipedia_processed["train"],
        jeopardy_processed["train"],
        riddle_processed["train"],
    ],
    axis=0,
)  # Automatically handles missing columns

"""Reward functions"""


# def perplexity_reward_func(prompts, completions, **kwargs):
#     """
#     Reward function based on perplexity. Lower perplexity = higher reward.
#     """
#     rewards = []
#     for completion in completions:
#         # Skip empty completions
#         if not completion or (isinstance(completion, list) and not completion[0]):
#            rewards.append(0.0)
#            continue

#         text = completion if isinstance(completion, str) else completion[0]
#         tokens = tokenizer(text, return_tensors="pt", truncation=True, padding="max_length", max_length=512)

#         tokens = {k: v.to(model.device) for k, v in tokens.items()}  # Move to GPU if needed

#         with torch.no_grad():
#             outputs = model(**tokens, labels=tokens["input_ids"].clone())
#             if hasattr(outputs, "loss") and outputs.loss is not None:
#                 loss = outputs.loss.item()
#                 rewards.append(-loss)  # Lower loss = higher reward
#             else:
#                 rewards.append(0.0)  # Default reward if loss is missing

#     return rewards


def diversity_reward(prompts, completions, **kwargs):
    rewards = []
    for completion in completions:
        words = completion.split()
        unique_words = set(words)
        diversity_score = len(unique_words) / max(
            1, len(words)
        )  # Ratio of unique words
        rewards.append(diversity_score)  # Higher is better
    return rewards


def length_reward(prompts, completions, **kwargs):
    rewards = []
    for completion in completions:
        length = len(completion.split())  # Count words
        if length < 5:  # Avoid one-word responses
            rewards.append(-1)  # Penalize too short
        elif length > 50:  # Penalize too long
            rewards.append(-(length - 50) / 10)
        else:
            rewards.append(1)  # Ideal length
    return rewards


"""<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!
"""


training_args = GRPOConfig(
    use_vllm=True,  # use vLLM for fast inference!
    learning_rate=5e-6,
    adam_beta1=0.9,
    adam_beta2=0.99,
    weight_decay=0.1,
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    optim="paged_adamw_8bit",
    logging_steps=1,
    bf16=is_bfloat16_supported(),
    fp16=not is_bfloat16_supported(),
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,  # Increase to 4 for smoother training
    num_generations=6,  # Decrease if out of memory
    max_prompt_length=256,
    max_completion_length=200,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps=250,
    save_steps=250,
    max_grad_norm=0.1,
    report_to="none",  # Can use Weights & Biases
    output_dir="outputs",
)

"""And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

"""

# training_args.max_steps = 1000  # Increase steps to prevent early stopping
# training_args.num_train_epochs = 3  # Run longer for better training

training_args.per_device_train_batch_size = 4  # Increase from 1 to 4
training_args.gradient_accumulation_steps = 4  # Helps with small batch sizes

trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    reward_funcs=[
        # perplexity_reward_func,
        # length_reward_func,
        length_reward,  # Keep responses concise but informative
        diversity_reward,  # Prevent excessive repetition
    ],
    args=training_args,
    train_dataset=final_dataset,  # combined dataset
)

trainer.train()

"""<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:
"""

text = tokenizer.apply_chat_template(
    [
        {
            "role": "user",
            "content": "What is the riddle of the sphinx, and what are all possible answers satisfying all conditions?",
        },
    ],
    tokenize=False,
    add_generation_prompt=True,
)


sampling_params = SamplingParams(
    temperature=0.8,
    top_p=0.95,
    max_tokens=1024,
)
output = (
    model.fast_generate(
        [text],
        sampling_params=sampling_params,
        lora_request=None,
    )[0]
    .outputs[0]
    .text
)

output

"""And now with the LoRA we just trained with GRPO - we first save the LoRA first!"""

model.save_lora("grpo_saved_lora")

text = tokenizer.apply_chat_template(
    [
        {
            "role": "user",
            "content": "If it takes 1 hour for 60 people to play an opera, how many hours will it take 600 people to play the same opera?",
        },
        {
            "role": "user",
            "content": "Is a pound of feathers or a British pound heavier?",
        },
        {
            "role": "user",
            "content": "A boy runs down the stairs in the morning and sees a tree in his living room, and some boxes under the tree. What's going on?",
        },
        {"role": "user", "content": "What happens if you crack your knuckles a lot?"},
        {
            "role": "user",
            "content": "If there is a shark in the pool of my basement, is it safe to go upstairs?",
        },
        {
            "role": "user",
            "content": "How much wood could a woodchuck chuck if there were only 5 pounds of wood in the world?",
        },
        {
            "role": "user",
            "content": "Who is the current President of the United States?",
        },
        {"role": "user", "content": "Was Talos alive?"},
        {"role": "user", "content": "How many Ls are in the word parallel?"},
        {
            "role": "user",
            "content": "What is the riddle of the sphinx, and what are all possible answers satisfying all conditions?",
        },
    ],
    tokenize=False,
    add_generation_prompt=True,
)


sampling_params = SamplingParams(
    temperature=0.8,
    top_p=0.95,
    max_tokens=1024,
)

output = (
    model.fast_generate(
        [text],
        sampling_params=sampling_params,
        lora_request=None,
    )[0]
    .outputs[0]
    .text
)

output

# Save the fine-tuned model
trainer.save_model("./wiki_tuned")

# Optionally, save the tokenizer too for later reloading
tokenizer.save_pretrained("./wiki_tuned")

"""Now we load the LoRA and test:"""

text = tokenizer.apply_chat_template(
    [
        # {"role" : "system", "content" : SYSTEM_PROMPT},
        {"role": "user", "content": "Give me a riddle"},
    ],
    tokenize=False,
    add_generation_prompt=True,
)


sampling_params = SamplingParams(
    temperature=0.8,
    top_p=0.95,
    max_tokens=1024,
)
output = (
    model.fast_generate(
        text,
        sampling_params=sampling_params,
        lora_request=model.load_lora("grpo_saved_lora"),
    )[0]
    .outputs[0]
    .text
)

output
