# -*- coding: utf-8 -*-
"""RileyAssn7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZNGIKF1fu2VJveRgBuwYoO_WQZm22ED

### Installation
"""  # from langchain.llms import LlamaCpp

from langchain_community.embeddings import HuggingFaceEmbeddings

# import torch
from langchain_community.vectorstores import Chroma
import pandas as pd

# Load Embedding Model
embed_model = HuggingFaceEmbeddings(model_name="Snowflake/snowflake-arctic-embed-l")

"""### Unsloth

Use `PatchFastRL` before all functions to patch GRPO and other RL algorithms!

### Data Prep
<a name="Data"></a>

Using the yoda stuff
"""


path = "/content/drive/MyDrive/Misc College/LLMs/data/yoda-corpus.csv"

df = pd.read_csv(path)
df_yoda = df[df["character"] == "YODA"]

df_yoda["text"]

"""Tokenizing the yoda dataset

"""

df_yoda["embedding"] = df_yoda["text"].apply(lambda x: embed_model.embed_query(x))

"""Embeddings"""

# Initialize ChromaDB with Hugging Face embeddings
vector_store = Chroma(persist_directory="./chroma_db", embedding_function=embed_model)

# Store Embeddings
for i, row in df_yoda.iterrows():
    vector_store.add_texts(
        texts=[row["text"]],
        metadatas=[{"character": "YODA"}],
        ids=[str(i)],
        embeddings=[row["embedding"]],
    )

vector_store.persist()


def query_vector_db(query, k=3):
    query_embedding = embed_model.embed_query(query)
    results = vector_store.similarity_search_by_vector(query_embedding, k)
    return [res.page_content for res in results]


# Example Query
query_result = query_vector_db("Tell me about the dangerous Sith")
print(query_result)
