# -*- coding: utf-8 -*-
"""Llama3.2_(1B)_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aed7DgtR92zk2xT5U8ywO3lWpP0HeJOr
"""

# Commented out IPython magic to ensure Python compatibility.
# # @title Install Required Packages
# %%capture
# !pip install unsloth
# !pip install transformers>=4.38.0
# !pip install datasets
# !pip install peft>=0.7.0
# !pip install bitsandbytes>=0.41.0
# !pip install accelerate>=0.25.0
# !pip install trl>=0.7.4
# !pip install zenml==0.71.0
# !pip install pandas
# !pip install torch
# 
# import os
# import sys
# import json
# import re
# import torch
# from pathlib import Path
# from typing import Dict, List, Tuple, Any
# from typing_extensions import Annotated
# from datasets import Dataset
# from tqdm.auto import tqdm

# @title Initialize ZenML

# Set your ZenML server URL
zenml_server_url = "https://zenml.mattburns.info" # Replace with your ZenML server URL in the form "https://URL_TO_SERVER"

# Verify values are set
assert zenml_server_url is not None, "Please set your ZenML server URL"

# Connect to ZenML server
!zenml login $zenml_server_url

# Disable wandb
import os
os.environ["WANDB_DISABLED"] = "true"

# Initialize ZenML and define the root for imports and docker builds
!zenml init

# Set default stack
!zenml stack set default

# Initialize client for ZenML operations
from zenml.client import Client
from zenml import step, pipeline, Model, log_artifact_metadata, save_artifact, log_metadata
from zenml.logger import get_logger

client = Client()
logger = get_logger(__name__)

print(f"Connected to ZenML server at {client.zen_store.url}")

# Disable wandb if not using it
os.environ["WANDB_DISABLED"] = "true"

hf_token = "" # Replace with your Hugging Face token

# Check if token is provided
assert hf_token is not None, "Please provide your Hugging Face token to access Llama models"

# Log in to Hugging Face
from huggingface_hub import login
login(token=hf_token)# Llama 3.2 1B Finetuning for Assignment 6

# @title Define Test Questions and System Prompt

TEST_QUESTIONS = [
    "If it takes 1 hour for 60 people to play an Opera, how many hours will it take 600 people to play the same opera?",
    "Is a pound of feathers or a British pound heavier?",
    "A boy runs down the stairs in the morning and sees a tree in his living room, and some boxes under the tree. What's going on?",
    "What happens if you crack your knuckles a lot?",
    "If there is a shark in the pool of my basement, is it safe to go upstairs?",
    "How much wood could a wood chuck chuck if there were only 5 pounds of wood in the world?",
    "Who is the current President of the United States?",
    "Was Talos alive?",
    "How many Ls are in the word parallel?",
    "What is the riddle of the sphinx, and what are all possible answers satisfying all conditions?"
]

# System prompt for our model
SYSTEM_PROMPT = """You are a helpful, harmless, and precise assistant. When responding, first think through the problem step-by-step, then provide your final answer.

Respond in the following format:
<reasoning>
[Your step-by-step thinking about the problem]
</reasoning>
<answer>
[Your final, concise answer]
</answer>
"""

# @title Create Training Dataset

# Sample instruction dataset for training
SAMPLE_DATA = [
    {
        "instruction": "If 5 workers can build a wall in 10 hours, how many hours will it take 10 workers to build the same wall?",
        "response": "<reasoning>\nLet's think about this problem. If 5 workers can build a wall in 10 hours, that means the total amount of work required is 5 workers × 10 hours = 50 worker-hours.\n\nIf we now have 10 workers, they will complete the work in 50 worker-hours ÷ 10 workers = 5 hours.\n</reasoning>\n<answer>\n5 hours\n</answer>"
    },
    {
        "instruction": "Is a kilogram of iron heavier than a kilogram of cotton?",
        "response": "<reasoning>\nThis question is asking me to compare the weight of a kilogram of iron and a kilogram of cotton.\n\nA kilogram is a unit of mass. One kilogram of any substance has the same mass as one kilogram of any other substance, by definition.\n\nSo a kilogram of iron has exactly the same mass as a kilogram of cotton.\n</reasoning>\n<answer>\nNo, a kilogram of iron is not heavier than a kilogram of cotton. They both have the same mass of exactly one kilogram.\n</answer>"
    },
    {
        "instruction": "A woman wakes up in the middle of the night and hears a loud thumping on her roof. When she goes outside in the morning, she sees small footprints on her roof. What might have happened?",
        "response": "<reasoning>\nLet me think about what could cause thumping on a roof at night and leave small footprints:\n\n1. Animals like squirrels, raccoons, or birds could walk on a roof and make noise\n2. Santa Claus in folklore is said to land on roofs with reindeer\n3. Weather events like hail could make thumping sounds but wouldn't leave footprints\n4. Tree branches could hit the roof but wouldn't leave footprints\n\nThe key clues are: thumping sound + small footprints. This most likely indicates some type of animal was walking on the roof.\n</reasoning>\n<answer>\nSmall animals like squirrels or raccoons were likely walking on her roof during the night.\n</answer>"
    },
    {
        "instruction": "What happens to your bones if you don't drink milk regularly?",
        "response": "<reasoning>\nLet's think about what milk provides and how it relates to bone health:\n\n1. Milk contains calcium, which is important for bone health and strength\n2. Milk also contains vitamin D, which helps with calcium absorption\n3. Not drinking milk doesn't necessarily lead to bone problems if you get these nutrients from other sources\n4. Many people around the world don't consume dairy but maintain healthy bones through other calcium-rich foods\n5. Factors like genetics, exercise, and overall diet also affect bone health\n</reasoning>\n<answer>\nNot drinking milk regularly doesn't necessarily harm your bones as long as you get calcium and vitamin D from other sources in your diet. Many non-dairy foods like leafy greens, fortified plant milks, tofu, and certain fish can provide these nutrients. Regular weight-bearing exercise is also important for maintaining bone density.\n</answer>"
    },
    {
        "instruction": "If there's a shark in my swimming pool, is it safe to go in my kitchen?",
        "response": "<reasoning>\nLet me think through this step by step:\n\n1. A shark in a swimming pool would be contained in that pool, assuming it's a normal residential pool\n2. Sharks cannot move on land or through air, so they cannot leave the pool on their own\n3. The kitchen is a separate location from the pool, typically inside the house\n4. There is no physical way for a shark to move from a pool to the kitchen\n\nSince the shark is physically confined to the pool and cannot reach the kitchen, there would be no direct danger from the shark in the kitchen.\n</reasoning>\n<answer>\nYes, it is completely safe to go in your kitchen if there's a shark in your swimming pool. The shark cannot leave the water or move into your house.\n</answer>"
    },
    {
        "instruction": "How much wood could a woodchuck chuck if a woodchuck had 8 hours to chuck wood?",
        "response": "<reasoning>\nThis is a play on the tongue twister \"How much wood could a woodchuck chuck if a woodchuck could chuck wood?\"\n\nTo answer this, I need to consider:\n1. The question is hypothetical since woodchucks (groundhogs) don't actually \"chuck\" (throw) wood\n2. There is a paper by wildlife biologist Richard Thomas who calculated that a woodchuck could chuck about 700 pounds of wood if woodchucks could chuck wood\n3. If we assume this rate is over a standard workday (8 hours), then a woodchuck chucks at a rate of about 87.5 pounds per hour\n4. Given exactly 8 hours, a woodchuck would chuck 8 × 87.5 = 700 pounds of wood\n</reasoning>\n<answer>\nIf we use the humorous calculation from wildlife biology, a woodchuck could chuck approximately 700 pounds of wood in 8 hours.\n</answer>"
    },
    {
        "instruction": "Who was the first female Vice President of the United States?",
        "response": "<reasoning>\nLet me go through the history of U.S. Vice Presidents:\n\n1. For most of U.S. history, all Vice Presidents were men\n2. Prior to the 2020 election, there had never been a female Vice President\n3. In the 2020 election, Kamala Harris was elected as Vice President alongside President Joe Biden\n4. She was inaugurated on January 20, 2021\n5. This made Kamala Harris the first female Vice President in U.S. history\n</reasoning>\n<answer>\nKamala Harris is the first female Vice President of the United States.\n</answer>"
    },
    {
        "instruction": "In Greek mythology, was Icarus alive at the end of his story?",
        "response": "<reasoning>\nLet me recall the myth of Icarus:\n\n1. Icarus and his father Daedalus were imprisoned in Crete by King Minos\n2. Daedalus created wings made of feathers, wax, and twine for them to escape\n3. Daedalus warned Icarus not to fly too close to the sun, as the heat would melt the wax\n4. During their escape, Icarus became excited and flew too high, despite his father's warnings\n5. The sun melted the wax holding his wings together\n6. Icarus fell into the sea (later named the Icarian Sea in his honor) and drowned\n</reasoning>\n<answer>\nNo, Icarus was not alive at the end of his story. According to Greek mythology, he drowned after falling into the sea when the wax in his wings melted.\n</answer>"
    },
    {
        "instruction": "How many E's are in the word 'excellence'?",
        "response": "<reasoning>\nLet me count the letters in the word 'excellence' one by one:\ne-x-c-e-l-l-e-n-c-e\n\nThe letter 'e' appears in positions 1, 4, 8, and 10.\n\nSo there are 4 instances of the letter 'e' in the word 'excellence'.\n</reasoning>\n<answer>\nThere are 4 E's in the word 'excellence'.\n</answer>"
    },
    {
        "instruction": "What is the riddle that asks \"what walks on four legs in the morning, two legs in the afternoon, and three legs in the evening\"? What is the answer to this riddle?",
        "response": "<reasoning>\nThis is the famous Riddle of the Sphinx from Greek mythology. In the story of Oedipus, the Sphinx asked this riddle to travelers attempting to enter the city of Thebes, killing those who couldn't solve it.\n\nThe riddle goes: \"What walks on four legs in the morning, two legs in the afternoon, and three legs in the evening?\"\n\nThe answer is \"a human being\" or \"man\", because:\n1. In the \"morning\" of life (infancy/childhood), humans crawl on all fours\n2. In the \"afternoon\" of life (adulthood), humans walk on two legs\n3. In the \"evening\" of life (old age), humans often use a cane or walking stick as a third \"leg\" for support\n\nThe times of day are metaphors for the stages of human life.\n</reasoning>\n<answer>\nThe riddle is the Riddle of the Sphinx: \"What walks on four legs in the morning, two legs in the afternoon, and three legs in the evening?\"\n\nThe answer is \"a human being\" or \"man\" - crawling as a baby (four legs), walking upright as an adult (two legs), and using a cane in old age (three legs).\n</answer>"
    }
]

@step
def create_dataset() -> Annotated[Dataset, "training_dataset"]:
    """Create a dataset for instruction tuning."""
    # Load high-quality reasoning dataset
    dataset = load_dataset('openai/gsm8k', 'main')['train']

    # Simple formatting function
    def format_example(example):
        return {
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": example['question']}
            ],
            "target": f"<reasoning>\n{example['answer']}\n</reasoning>\n<answer>\n{example['answer'].split('####')[-1].strip()}\n</answer>"
        }

    # Apply formatting
    formatted_dataset = dataset.map(format_example)

    # Add original sample data
    original_data = [
        {
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": item["instruction"]}
            ],
            "target": item["response"]
        } for item in SAMPLE_DATA
    ]

    # Combine datasets
    full_dataset = Dataset.from_list(list(formatted_dataset) + original_data)

    logger.info(f"Created dataset with {len(full_dataset)} examples")

    return full_dataset

# @title Helper Functions

def extract_structured_answer(text):
    """Extract reasoning and answer sections from a structured response."""
    # Default values
    reasoning = ""
    answer = ""

    # Extract reasoning section
    reasoning_pattern = r"<reasoning>(.*?)</reasoning>"
    reasoning_match = re.search(reasoning_pattern, text, re.DOTALL)
    if reasoning_match:
        reasoning = reasoning_match.group(1).strip()

    # Extract answer section
    answer_pattern = r"<answer>(.*?)</answer>"
    answer_match = re.search(answer_pattern, text, re.DOTALL)
    if answer_match:
        answer = answer_match.group(1).strip()

    # If no structured format found, use the entire text as the answer
    if not reasoning and not answer:
        answer = text.strip()

    return reasoning, answer

# Define reward functions for format compliance
def strict_format_reward_func(text):
    """Reward function that checks if the text has the expected structure."""
    pattern = r"^<reasoning>\n.*?\n</reasoning>\n<answer>\n.*?\n</answer>\n$"
    match = re.match(pattern, text, re.DOTALL)
    return 1.0 if match else 0.0

def soft_format_reward_func(text):
    """Reward function with more lenient formatting requirements."""
    pattern = r"<reasoning>.*?</reasoning>\s*<answer>.*?</answer>"
    match = re.search(pattern, text, re.DOTALL)
    return 1.0 if match else 0.0

# @title Train the Model

@step
def train_llama_model(
    dataset: Dataset,
    huggingface_model_name: str = "meta-llama/Llama-3.2-1B-Instruct",
    max_seq_length: int = 512,
    lora_rank: int = 16,
    num_train_epochs: int = 3,
    learning_rate: float = 2e-5,
    per_device_train_batch_size: int = 1,
    gradient_accumulation_steps: int = 4,
    output_dir: str = "llama_finetuned"
) -> Annotated[Dict[str, Any], "model_info"]:
    """Train Llama 3.2:1B model with Unsloth."""
    # Import Unsloth and Accelerate
    from unsloth import FastLanguageModel
    from accelerate import Accelerator
    import torch
    from transformers import TrainingArguments, Trainer

    # Create or get the model for ZenML tracking
    zenml_model_name = "Assn6LLMFinetune"

    # Check if the model exists
    try:
        # Try to get the model by name
        model = client.get_model(zenml_model_name)
        logger.info(f"Found existing model: {zenml_model_name}")
    except KeyError:
        # Model doesn't exist, create it
        logger.info(f"Creating new model: {zenml_model_name}")
        model = client.create_model(
            name=zenml_model_name,
            description="Llama 3.21B model finetuned for Assignment 6",
            tags=["llama", "instruction-tuning", "assignment"]
        )

    # # Create a version of this model
    # model_version = client.create_model_version(
    #     model_name_or_id=model.id,
    #     name=f"v{(len(model.versions) if hasattr(model, 'versions') else 0) + 1}"
    # ).id
    # logger.info(f"Created model version: {model_version}")

    # Check if CUDA is available
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Using device: {device}")

    # Split dataset
    train_test_split = dataset.train_test_split(test_size=0.1, seed=42)
    train_dataset = train_test_split["train"]
    eval_dataset = train_test_split["test"]

    # Load model and tokenizer with Unsloth - using the HuggingFace model name!
    logger.info(f"Loading model {huggingface_model_name}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="meta-llama/Llama-3.2-1B-Instruct",  # Hardcoded correct HF model name
        max_seq_length=max_seq_length,
        load_in_4bit=True,  # Use 4-bit quantization
        token=hf_token,  # Use the HF token for authentication
    )

    # Apply LoRA
    model = FastLanguageModel.get_peft_model(
        model,
        r=lora_rank,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        lora_alpha=lora_rank,
        lora_dropout=0.05,
        use_gradient_checkpointing="unsloth",
    )

    # Log model parameters
    model_params = {
        "model_name": huggingface_model_name,  # Log the actual HuggingFace model name
        "lora_rank": lora_rank,
        "trainable_parameters": sum(p.numel() for p in model.parameters() if p.requires_grad),
        "total_parameters": sum(p.numel() for p in model.parameters()),
    }
    log_artifact_metadata(model_params)

    # Prepare tokenization function
    def tokenize_function(example):
        # Format messages into conversation
        messages = example["messages"]
        prompt = ""
        for msg in messages:
            prompt += f"{msg['role'].upper()}: {msg['content']}\n\n"

        # Tokenize input and target
        inputs = tokenizer(prompt, return_tensors="pt", padding="max_length",
                          max_length=max_seq_length, truncation=True)
        targets = tokenizer(example["target"], return_tensors="pt", padding="max_length",
                           max_length=max_seq_length, truncation=True)

        return {
            "input_ids": inputs.input_ids[0],
            "attention_mask": inputs.attention_mask[0],
            "labels": targets.input_ids[0]
        }

    # Process the datasets
    logger.info("Tokenizing datasets")
    tokenized_train = train_dataset.map(tokenize_function, remove_columns=train_dataset.column_names)
    tokenized_eval = eval_dataset.map(tokenize_function, remove_columns=eval_dataset.column_names)

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Set up training arguments
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=per_device_train_batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        fp16=True,
        logging_steps=5,
        evaluation_strategy="steps",
        eval_steps=25,
        save_strategy="steps",
        save_steps=25,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="none",  # Don't use wandb, etc.
        max_grad_norm=1.0,
        optim="adamw_torch",  # More memory-efficient optimizer
    )

    class ZenMLLoggingCallback:
        def __init__(self):
            pass

        def on_init_end(self, args, state, control):
            # Simply return the control as-is
            return control

        def on_log(self, args, state, control, logs=None, **kwargs):
            if logs:
                for key, value in logs.items():
                    if isinstance(value, (int, float)):
                        log_artifact_metadata({key: value})


    # Initialize Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_eval,
        # callbacks=[ZenMLLoggingCallback()],
    )

    # Train the model
    logger.info("Starting training...")
    train_result = trainer.train()

    # Log final metrics
    final_metrics = {
        "train_loss": train_result.metrics.get("train_loss", 0),
        "train_runtime": train_result.metrics.get("train_runtime", 0),
        "train_samples_per_second": train_result.metrics.get("train_samples_per_second", 0),
    }

    # Evaluate the model
    logger.info("Evaluating model...")
    eval_metrics = trainer.evaluate()

    # Combine metrics
    final_metrics.update({
        "eval_loss": eval_metrics.get("eval_loss", 0),
    })

    # Log final metrics
    log_artifact_metadata(final_metrics)

    logger.info(f"Saving model to {output_dir}")
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)

    return {
        "model_path": output_dir,
        "tokenizer_path": output_dir,
        "model_name": zenml_model_name
    }

# @title Test the Model

@step
def test_model(
    model_info: Dict[str, Any],
    max_new_tokens: int = 256
) -> Annotated[Dict[str, Any], "evaluation_results"]:
    """Test the fine-tuned model on the assignment questions."""
    from unsloth import FastLanguageModel

    # Load the model from the saved path
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_info["model_path"],
        max_seq_length=512,
        load_in_4bit=True,
        token=hf_token,
        gpu_memory_utilization=0.8,
    )

    # Prepare the model for inference
    model = FastLanguageModel.for_inference(model)

    # Generation parameters
    generation_params = {
        "max_new_tokens": max_new_tokens,
        "temperature": 0.7,
        "top_p": 0.95,
        "top_k": 50,
    }

    # Prepare results storage
    results = {
        "questions": TEST_QUESTIONS,
        "answers": [],
        "formatted_qa_pairs": []
    }

    # Test metrics
    format_compliance = []

    # Answer each question
    logger.info("Answering test questions...")

    for question in tqdm(TEST_QUESTIONS):
        # Format as chat
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": question}
        ]

        # Format prompt
        prompt = ""
        for msg in messages:
            prompt += f"{msg['role'].upper()}: {msg['content']}\n\n"

        # Tokenize
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

        # Generate answer
        with torch.no_grad():
            outputs = model.generate(
                inputs.input_ids,
                **generation_params
            )

        # Decode the generated output
        generated_text = tokenizer.decode(outputs[0][len(inputs.input_ids[0]):], skip_special_tokens=True)

        # Extract reasoning and answer
        reasoning, answer = extract_structured_answer(generated_text)

        # Check format compliance
        strict_format = strict_format_reward_func(generated_text)
        soft_format = soft_format_reward_func(generated_text)
        format_compliance.append({"strict": strict_format, "soft": soft_format})

        # If no structured answer found, use the whole text
        if not answer:
            answer = generated_text

        # Add to results
        results["answers"].append({
            "question": question,
            "full_response": generated_text,
            "reasoning": reasoning,
            "final_answer": answer,
            "format_compliance_strict": strict_format,
            "format_compliance_soft": soft_format,
        })

        # Add to formatted Q&A pairs
        results["formatted_qa_pairs"].append(f"Q: {question}\nA: {answer}")

    # Calculate format compliance metrics
    strict_compliance_rate = sum(item["strict"] for item in format_compliance) / len(format_compliance)
    soft_compliance_rate = sum(item["soft"] for item in format_compliance) / len(format_compliance)

    # Log metrics to ZenML
    evaluation_metrics = {
        "format_compliance_strict": strict_compliance_rate,
        "format_compliance_soft": soft_compliance_rate,
        "num_questions": len(TEST_QUESTIONS),
    }
    log_artifact_metadata(evaluation_metrics)

    # Save answers.txt file
    with open("answers.txt", "w") as f:
        for qa in results["formatted_qa_pairs"]:
            f.write(f"{qa}\n\n")

    logger.info(f"Answers saved to answers.txt")
    logger.info(f"Format compliance: Strict={strict_compliance_rate:.2f}, Soft={soft_compliance_rate:.2f}")

    return results

# @title Run the Complete Pipeline

@pipeline
def llama_finetuning_pipeline(
    huggingface_model_name: str = "meta-llama/Llama-3.2-1B-Instruct",
    max_length: int = 1024,
    lora_rank: int = 16,
    learning_rate: float = 2e-5,
    num_train_epochs: int = 3,
    per_device_train_batch_size: int = 8,
    gradient_accumulation_steps: int = 2,
):
    """Pipeline for finetuning Llama 3.2:1B on instruction data."""
    # Create the dataset
    dataset = create_dataset()

    # Train the model
    model_info = train_llama_model(
        dataset=dataset,
        huggingface_model_name=huggingface_model_name,
        max_seq_length=max_length,
        lora_rank=lora_rank,
        learning_rate=learning_rate,
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=per_device_train_batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps
    )

    # Test on assignment questions
    results = test_model(
        model_info=model_info,
        max_new_tokens=256
    )

    return model_info, results

# Run the pipeline when this cell is executed
if __name__ == "__main__":
    llama_finetuning_pipeline()

# @title Examine Model Answers (run after training is complete)
# @markdown Display the model's answers for all test questions

def show_model_answers(results):
    """Display the model's answers for all test questions."""
    for i, (question, answer) in enumerate(zip(TEST_QUESTIONS, results["answers"])):
        print(f"Question {i+1}: {question}")
        print(f"Answer: {answer['final_answer']}")
        print("-" * 80)

# Example usage:
# model_info, results = run_pipeline()  # If you haven't run the pipeline yet
# show_model_answers(results)  # Display all answers